In [11]:
import pandas as pd

datos_restaurantes = {
    'id_del_restaurante': [1,2],
    'name': ['La parrilla', 'Sushi'],
    'category': ['Carnes', 'Comida Japonesa']
}
df_restaurantes = pd.DataFrame(datos_restaurantes)

In [10]:
datos_menus = {
    'id_menu': [101,102,103,104],
    'restaurante_id': [1,1,2,3],
    'name': ['Menu 1', 'Menu 2', 'Menu 3', 'Menu 4'],
    'category': ['Almuerzo', 'Almuerzo', 'Cena', 'Cena']
}
df_menus = pd.DataFrame(datos_menus)

In [16]:
df_master_problema = pd.merge(df_restaurantes, df_menus, on='id_restaurante')
print(df_master_problema)

KeyError: 'id_restaurante'

In [6]:
df_master_sufijos = pd.merge(
    df_restaurantes,
    df_menus,
    on='id_restaurante',
    suffixes=('_restaurantes', '_menus')
    )
display(df_master_sufijos)

,id_restaurante,name_restaurantes,category_restaurantes,id_menu,name_menus,category_menus
0,1,La parrilla,Carnes,101,Menu 1,Almuerzo
1,1,La parrilla,Carnes,102,Menu 2,Almuerzo
2,2,Sushi,Comida Japonesa,103,Menu 3,Cena
3,2,Sushi,Comida Japonesa,104,Menu 4,Cena

In [15]:
df_master_sufijos_2 = pd.merge(
    df_menus,
    df_restaurantes,
    left_on='restaurante_id',
    right_on='id_del_restaurante',
    suffixes=('_rest', '_platos'),
    how='left'
    )
display(df_master_sufijos_2)

,id_menu,restaurante_id,name_rest,category_rest,id_del_restaurante,name_platos,category_platos
0,101,1,Menu 1,Almuerzo,1.0,La parrilla,Carnes
1,102,1,Menu 2,Almuerzo,1.0,La parrilla,Carnes
2,103,2,Menu 3,Cena,2.0,Sushi,Comida Japonesa
3,104,3,Menu 4,Cena,NaN,NaN,NaN

In [ ]:
df_menus
	restaurant_id	category	name	description	price

In [ ]:
df_restaurantes
id	position	name	score	ratings	category	price_range	full_address	zip_code	lat	lng	calle	ciudad	estado_zip

In [ ]:
df_master_sufijos_2 = pd.merge(
    df_menus,
    df_restaurantes,
    left_on='restaurant_id',
    right_on='id',
    suffixes=('_rest', '_menus'),
    how='inner'
    )
display(df_master_sufijos_2)

In [ ]:
df_restaurantes.rename(columns={"id": "restaurant_id"}, inplace=True)

In [ ]:
df_restaurantes
restaurant_id	position	name	score	ratings	category	price_range	full_address	zip_code	lat	lng	calle	ciudad	estado_zip

In [ ]:
df_master_sufijos = pd.merge(
    df_restaurantes,
    df_menus,
    on='restaurant_id',
    suffixes=('_rests', '_menus'),
    how='inner'
    )
display(df_master_sufijos)

In [17]:
datos = {
    'id_restaurante': [1, 2, None, 4, 5],
    'restaurante_id': [1, None, 3, 4, None],
    'name': ['La Parrilla', 'Sushi Master', 'Pasta Express', 'Burger House', 'Tacos Express']
}
df = pd.DataFrame(datos)
print("--- DATOS ORIGINALES ---")
print(df)

--- DATOS ORIGINALES ---
   id_restaurante  restaurante_id           name
0             1.0             1.0    La Parrilla
1             2.0             NaN   Sushi Master
2             NaN             3.0  Pasta Express
3             4.0             4.0   Burger House
4             5.0             NaN  Tacos Express

In [18]:
print(df.isnull().sum())

id_restaurante    1
restaurante_id    2
name              0
dtype: int64

In [20]:
filas_nulas = df[df['id_restaurante'].isnull()]
print(filas_nulas)

   id_restaurante  restaurante_id           name
2             NaN             3.0  Pasta Express